`timescale 1ns/1ps

// ================================================================
// @file     tb_aes_sbox.sv
// @brief    Stage 1: AES S-box exhaustive verification
// @details
//   Golden reference loaded from vectors/sbox_golden.hex via
//   $readmemh. Generated by scripts/gen_sbox_golden.py from
//   GF(2^8) math - not hand typed.
//
//   Run from repo root (sim.mk handles this via cd $(PROJECT_ROOT)):
//     make vectors    <- generate sbox_golden.hex first
//     make sim-sbox   <- compile, elaborate, simulate
//
//   Pass criteria: 256/256 PASS, $fatal not triggered.
// ================================================================

module tb_aes_sbox;

    logic [7:0] in_byte;
    logic [7:0] out_byte;

    // FIX 1: golden must be declared at module scope, not inside initial
    logic [7:0] golden [0:255];

    int pass_count;
    int fail_count;

    // DUT
    aes_sbox dut (
        .in_byte  (in_byte),
        .out_byte (out_byte)
    );

    initial begin
        // FIX 2: path is relative to PROJECT_ROOT (sim.mk does cd before xsim)
        // matches VEC_DIR := $(PROJECT_ROOT)/vectors in sim.mk
        $readmemh("vectors/sbox_golden.hex", golden);

        pass_count = 0;
        fail_count = 0;

        $display("");
        $display("================================");
        $display(" Stage 1: AES S-box Verification");
        $display(" Golden: vectors/sbox_golden.hex");
        $display("================================");

        for (int i = 0; i < 256; i++) begin
            in_byte = i[7:0];
            #1; // combinatorial settle

            if (out_byte === golden[i]) begin
                pass_count++;
            end else begin
                // FIX 3: track failures, don't just print and continue
                $display("  [FAIL] SBOX[0x%02h]: expected 0x%02h  got 0x%02h",
                         i[7:0], golden[i], out_byte);
                fail_count++;
            end
        end

        $display("--------------------------------");
        $display("  Results: %0d PASS  %0d FAIL  (of 256)",
                 pass_count, fail_count);
        $display("================================");

        if (fail_count != 0) begin
            $display("  Cross-check aes_sbox.sv against FIPS 197 Figure 7.");
            $fatal(1, "S-box verification FAILED.");  // nonzero exit - make detects failure
        end else begin
            $display("  PASS - proceed to sim-core");
        end

        $finish;
    end

endmodule